const ACTIVITY_TYPES={
    CODE_RUN:"CODE_RUN",
    ACCEPTED:"ACCEPTED",
    ERROR_SOLVED:"ERROR_SOLVED",
    TIME_CHALLENGE:"TIME_CHALLENGE",
    DAILY_BONUS:"DAILY_BONUS",
    CHALLENGE_COMPLETE:"CHALLENGE_COMPLETE",
    PROJECT_MILESTONE:"PROJECT_MILESTONE",
    PROJECT_COMPLETE:"PROJECT_COMPLETE"
};
module.exports=ACTIVITY_TYPES;